# Dockerfile.fastapi
FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# create logs dir early (ensures permissions and folder exist)
RUN mkdir -p /app/logs

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# copy source and artifacts
COPY src/ ./src
COPY artifacts/ ./artifacts

# (optional) do not COPY .env into image for production; for local dev you can
# COPY .env .env

EXPOSE 8000

CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
